# Generated by Django 5.1.15 on 2026-09-29 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('actor_username', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('register', 'Register'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('vault_create', 'Vault Create'), ('vault_update', 'Vault Update'), ('vault_delete', 'Vault Delete'), ('share_create', 'Share Create'), ('share_rejected_signature', 'Share Rejected Signature'), ('share_accept', 'Share Accept'), ('share_delete', 'Share Delete'), ('role_change', 'Role Change'), ('user_status_change', 'User Status Change'), ('access_denied', 'Access Denied'), ('analyzer_run', 'Analyzer Run')], db_index=True, max_length=40)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
